CREATE DATABASE ECOMMERCE_DB;
USE ECOMMERCE_DB;

-- Criação das tabelas
CREATE TABLE CLIENTES (
ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR (50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
DATA_CADASTRO DATE NOT NULL
);

CREATE TABLE PRODUTOS(
ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
NOME_PRODUTO VARCHAR(30) NOT NULL,
PRECO FLOAT(10,2) NOT NULL,
ESTOQUE INT NOT NULL
);

CREATE TABLE PEDIDOS(
ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE INT NOT NULL,
DATA_PEDIDO DATE NOT NULL
);

ALTER TABLE PEDIDOS ADD CONSTRAINT FK_CLIENTE_PEDIDO
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
ON DELETE CASCADE
ON UPDATE CASCADE;

CREATE TABLE ITENS_PEDIDO(
ID_ITEM INT PRIMARY KEY AUTO_INCREMENT,
ID_PEDIDO INT NOT NULL,
ID_PRODUTO INT NOT NULL,
QUANTIDADE INT NOT NULL
);

ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT FK_PEDIDOS_ITENS_PEDIDO
FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT FK_PRODUTOS_ITENS_PEDIDO
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
ON DELETE CASCADE
ON UPDATE CASCADE;

CREATE TABLE LOG_ESTOQUE(
ID_LOG INT PRIMARY KEY AUTO_INCREMENT,
ID_PRODUTO INT NOT NULL,
DATA_MODIFICACAO DATETIME,
ACAO VARCHAR(100),
QUANTIDADE_AFETADA INT NOT NULL
);

ALTER TABLE LOG_ESTOQUE ADD CONSTRAINT FK_PRODUTOS_LOG_ESTOQUE
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- Inserindo os dados

INSERT INTO CLIENTES VALUES
(NULL, 'Ana Souza', 'ana@gmail.com', '2023-05-10'),
(NULL, 'Bruno Lima', 'bruno@gmail.com', '2023-06-15'),
(NULL, 'Carla Menezes', 'carla@hotmail.com', '2024-01-22');

INSERT INTO PRODUTOS VALUES
(NULL, 'Mouse', 59.9, 100),
(NULL, 'Teclado', 129.0, 50),
(NULL, 'Monitor 21"', 749.9, 30),
(NULL, 'Notebook', 3499.9, 10);

INSERT INTO PEDIDOS VALUES
(NULL, 1, '2024-03-02'),
(NULL, 1, '2024-06-10'),
(NULL, 2, '2024-06-15');

INSERT INTO ITENS_PEDIDO VALUES
(NULL, 1, 1, 2),
(NULL, 1, 2, 1),
(NULL, 2, 4, 1),
(NULL, 3, 3, 2);