-- USANDO O JOIN

-- Exibir todos os pedidos com nome e e-mail do cliente

SELECT P.ID_PEDIDO, P.DATA_PEDIDO, C.NOME, C.EMAIL
FROM PEDIDOS AS P JOIN CLIENTES AS C
ON P.ID_CLIENTE = C.ID_CLIENTE;

-- Listar os itens de um pedido com nome e preço dos produtos
-- OBS. Adicionei uma coluna 'Total', para saber a quantidade total

SELECT IP.ID_PEDIDO, P.NOME_PRODUTO, IP.QUANTIDADE, P.PRECO, (IP.QUANTIDADE*P.PRECO) AS TOTAL
FROM ITENS_PEDIDO AS IP JOIN PRODUTOS AS P
ON IP.ID_PRODUTO = P.ID_PRODUTO;

-- Listar os produtos comprados por “Ana Souza”

SELECT P.NOME_PRODUTO, IP.QUANTIDADE, PE.DATA_PEDIDO
FROM PRODUTOS AS P 
JOIN ITENS_PEDIDO AS IP ON P.ID_PRODUTO = IP.ID_PRODUTO
JOIN PEDIDOS AS PE ON IP.ID_PEDIDO = PE.ID_PEDIDO
JOIN CLIENTES AS C ON C.ID_CLIENTE = PE.ID_CLIENTE
WHERE C.NOME = 'Ana Souza';

-- Exibir o total vendido por produto

SELECT P.NOME_PRODUTO, SUM(IP.QUANTIDADE) AS TOTAL_VENDIDO
FROM PRODUTOS AS P JOIN ITENS_PEDIDO AS IP
ON P.ID_PRODUTO = IP.ID_PRODUTO
GROUP BY P.NOME_PRODUTO;

-- Exibir todos os clientes que já compraram “Notebook”

SELECT DISTINCT C.NOME, C.EMAIL, PE.DATA_PEDIDO
FROM CLIENTES AS C 
JOIN PEDIDOS AS PE ON C.ID_CLIENTE = PE.ID_CLIENTE
JOIN ITENS_PEDIDO AS IP ON IP.ID_PEDIDO = PE.ID_PEDIDO
JOIN PRODUTOS AS P ON IP.ID_PRODUTO = P.ID_PRODUTO
WHERE P.NOME_PRODUTO = 'Notebook';

-- STORE PROCEDURE

-- Criar uma procedure chamada fazer_pedido
DELIMITER & 
CREATE PROCEDURE FAZER_PEDIDO(IN P_ID_CLIENTE INT, IN P_ID_PRODUTO INT, IN P_QUANTIDADE INT)
BEGIN
	DECLARE V_NOVO_PEDIDO_ID INT;
    
    -- Criar pedido
	INSERT INTO PEDIDOS (ID_CLIENTE, DATA_PEDIDO) 
    VALUES (P_ID_CLIENTE, SYSDATE());
    
    -- Capturar o ID fo pedido recém-criado;
    SET V_NOVO_PEDIDO_ID = LAST_INSERT_ID();
    
    -- Inserir item do pedido
    
    INSERT INTO ITENS_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE) 
    VALUES(V_NOVO_PEDIDO_ID, P_ID_PRODUTO, P_QUANTIDADE);
    
    -- Atualizar estoque do produto
    UPDATE PRODUTOS 
    SET ESTOQUE = ESTOQUE - P_QUANTIDADE
    WHERE ID_PRODUTO = P_ID_PRODUTO; 
END
&

-- Criar uma procedure chamada listar_compras_cliente
DELIMITER $
CREATE PROCEDURE LISTAR_COMPRAS_CLIENTE(IN ID_CLIENTE INT)
BEGIN
	SELECT P.NOME_PRODUTO, IP.QUANTIDADE, PE.DATA_PEDIDO
    FROM PRODUTOS AS P 
    JOIN ITENS_PEDIDO AS IP ON P.ID_PRODUTO = IP.ID_PRODUTO
    JOIN PEDIDOS AS PE ON PE.ID_PEDIDO = IP.ID_PEDIDO
    WHERE PE.ID_CLIENTE = ID_CLIENTE;
END
$

-- Criar uma procedure chamada repor_estoque
DELIMITER @
CREATE PROCEDURE REPOR_ESTOQUE(IN P_ID_PRODUTO INT, IN P_QUANTIDADE INT)
BEGIN
	UPDATE PRODUTOS
    SET ESTOQUE = ESTOQUE + P_QUANTIDADE
    WHERE ID_PRODUTO = P_ID_PRODUTO;
    
    -- Mostrar o novo estoque
	SELECT ID_PRODUTO, NOME_PRODUTO, PRECO, ESTOQUE
    FROM PRODUTOS
    WHERE ID_PRODUTO = P_ID_PRODUTO;
END
@

